
  title: "My Learning Journal"
description: "A personal blog documenting my journey in Linux, networking, cybersecurity, and more."
url: "https://fightMMC0lub.github.io"
baseurl: "" # keep empty for root

author:
  name: "3#31200xsN"
  email: "getshop463@gmail.com"

theme: minima

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

# Social links (used in SEO / footer / meta tags)
social_links:
  github: https://github.com/fightMMC0lub
  linkedin: https://linkedin.com/in/fouad-azahaf-51a783335
  blog: https://the0xtechworld.blogspot.com

# Google Analytics (optional)
google_analytics: ""

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

