title: "My Learning Journal"
description: "My journey through Linux, networks, cybersecurity, and more."
url: "https://fightMMC0lub.github.io"
baseurl: "" # leave empty for user.github.io sites

author:
  name: "3#31200xsN"
  email: "getshop463@gmail.com"

theme: minima

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
