title: " ____ "
description: "-_-_-_-_-_-_-_-_-"
url: "https://fightMMC0lub.github.io"
baseurl: ""

author:
  name: "3#31200xsN"

theme: minima

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
